# Generated by Django 2.1.5 on 2019-02-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('1', "The Midnight Summer's Dream"), ('2', 'The Lowland'), ('3', 'The Norwegian Wood'), ('4', 'Fault in our Stars'), ('5', 'The Alchemist'), ('6', 'Power of the Subconscious Mind')], default=1, max_length=50, verbose_name='Book Name')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone_no', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shellentry.Student'),
        ),
    ]
